default:
  image: ghcr.io/prefix-dev/pixi:0.46.0
  before_script:
    - docker info

build_image:
  script:
    - docker build -t gitregistry.lumc.nl:4443/klinische-genetica/docker-flair-2.2.0 .
    - docker run -it gitregistry.lumc.nl:4443/klinische-genetica/docker-flair-2.2.0 flair --help

publish_image:
  script:
    - docker push gitregistry.lumc.nl:4443/klinische-genetica/docker-flair-2.2.0
